version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: "chess-games:1:1,movies:1:1"
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_JMX_PORT: 9999
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "9999:9999"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: spoud_data_catalog
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
