fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck
      - id: shfmt
        args: ["-w"]
