[character]
success_symbol = "[Λ](blue)"
error_symbol = "[x](red)"
vicmd_symbol = "[N](green)"

[directory]
style = "blue"
truncation_length = 0

[git_status]
ahead = "▲"
behind = "▼"

[nodejs]
symbol = "⬢ "
