theme = "spacebones_light"

[editor]
color-modes = true
cursorline = true
auto-format = false
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.insert]
# https://github.com/helix-editor/helix/pull/3671
C-a = "goto_line_start"
C-b = "move_char_left"
C-e = "goto_line_end_newline"
C-f = "move_char_right"

[keys.normal]
"=" = { "=" = ":fmt" }
