[[language]]
name = "bash"
formatter = { command = "shfmt" }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "go"
formatter = { command = "gofmt" }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "babel"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "python"
formatter = { command = "black", args = ["-"] }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--parser", "scss"] }

[[language]]
name = "sql"
formatter = { command = "pg_format" }

[[language]]
name = "starlark"
formatter = { command = "buildifier" }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
