name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project init
            project update
            do check
