name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: shellcheck ./utility/*.sh && find . -not -path './.git/*' -type f -perm -u=x | xargs -t -I {} shellcheck -x {}

      - name: Format
        run: npx prettier -l '**/*.{json,md,yaml,yml}'
