name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Shellcheck libraries
        run: shellcheck ./utility/*.sh

      - name: Shellcheck executables
        run: find . -not -path './.git/*' -type f -perm -u=x | xargs -t -I {} shellcheck -x {}

      - name: Prettier
        run: npx prettier -l '**/*.{json,yaml,yml}'
