name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: curl -L https://dl.dagger.io/dagger-cue/install.sh | sh
        working-directory: /usr/local

      - uses: actions/checkout@v3

      - run: dagger-cue project init && dagger-cue project update && dagger-cue do check
