name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install npm shellcheck shfmt -y
      - run: npx prettier -c .
      - run: shfmt -f . | xargs -t -I % shfmt -d %
      - run: shfmt -f . | xargs -t -I % shellcheck -x %
