name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install shfmt
        run: sudo snap install shfmt

      - name: Format Shell
        run: shfmt -f . | xargs -t -I % shfmt -d %

      - name: Format Prettier
        run: npx prettier -l '**/*.{json,md,yaml,yml}'

      - name: Lint
        run: shfmt -f . | xargs -t -I % shellcheck -x %
