name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bash libraries
        run: shellcheck ./utility/*.sh
      - name: Bash executables
        run: find . -not -path "./.git/*" -type f -perm -u=x | xargs -t -I {} shellcheck -x {}
      - name: Prettier
        run: yarn add prettier; prettier -l './**/*.{json,yaml,yml}
